### ISSUE TITLE
Move off of Heroku

### ISSUE THREAD

**Issue by elorest** [amberframework/amberframework.org#43]
### Description

Lets move the site from heroku to digital ocean or aws. 

### Benefits

1. Allow us to run a fast database 

2. Won't have to worry about the size of assets.

2. The site will load faster.

3. SSL can handled on server instead of cloudflare which is more secure.

4. I'm willing to host it on one of my servers if there is any interest in this.

### Draw backs

Harder to set up deploy on push to master.

**Comment by faustinoaq** [comment]
I think Heroku is good, but I'm not a server expert maybe I'm wrong 😅

**Comment by eliasjpr** [comment]
I don't see any benefits of moving to Digital Ocean. 

- Heroku Postgres DB are  fast and very stable
- The site is on a free plan and performs well
- SSL can be handle off to be managed by Heroku including the domain names, cloud flare just offers some benefits

**Comment by eliasjpr** [comment]
The hosting of amberframework on heroku is not an issue. 

Continuing stating the benefits

- We get github integration which allow automatic deployment
- automatic branch preview, heroku generate a preview app for each branch open that allow us to review the work before its deployed
- easy management since we don’t have to worry about Sever update configurations etc it just works
- it reduces the bus factor 100% since i already gave access to the team and no one person has full control of the site.
